name: CD

on:
  push:
    branches: ['main']

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: remote:rw
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Turborepo CLI
        run: npm install --global turbo

      - name: Enable and set pnpm version
        run: |
          corepack enable
          corepack prepare pnpm@9.5.0 --activate

      - name: Vercel link
        run: vercel link --yes --token=${{ secrets.TURBO_TOKEN }} --project=${{ secrets.VERCEL_PROJECT_NAME }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.TURBO_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.TURBO_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.TURBO_TOKEN }}
